### PR TITLE
Revert "Merge pull request #119 from emankov/emankov/nvcc"

### PR DESCRIPTION
**Pull request by david-salinas**
This reverts commit 93c2a54d462c8e02535e9867d3b9a18da5898977, reversing changes made to 863ece887cafdcf487a5c0c79db7a96ba80a96fb.

### CODE REVIEW

**Comment by kzhuravl** [comment]
> What's wrong with #119?

PR #119 breaks the PSDB, PR #119 was never tested on a PSDB. So I think it should be reverted until investigations are done.

image

cc @searlmc1

**Review by searlmc1 — APPROVED** [review]
LGTM

**Review by kzhuravl — CHANGES_REQUESTED** [review]
Let's see if we should land PR #127 instead of reverting PR #119

**Comment by kzhuravl** [comment]
Fix merged, so revert is not needed.

**Pull request closed without merging**
